name: Status Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Thêm các bước kiểm tra mã nguồn, linting, định dạng, v.v.
      # Ví dụ:
      # - name: Chạy các bài kiểm tra đơn vị
      #   run: gradlew.bat test

      # - name: Kiểm tra định dạng mã nguồn
      #   run: gradlew.bat spotlessCheck

      # - name: Kiểm tra lỗi linting trong mã nguồn
      #   run: gradlew.bat lint

  # Thêm các công việc khác cho các kiểm tra bổ sung nếu cần
